### ISSUE TITLE
Cant try

### ISSUE THREAD

**Issue by johnfelipe** [tdryer/Node-Whiteboard#1]
felipe@cloud:~$ git clone https://github.com/tdryer/Node-Whiteboard.git
	Cloning into 'Node-Whiteboard'...
	remote: Counting objects: 574, done.
	remote: Compressing objects: 100% (192/192), done.
	remote: Total 574 (delta 378), reused 574 (delta 378), pack-reused 0
	Receiving objects: 100% (574/574), 109.41 KiB | 0 bytes/s, done.
	Resolving deltas: 100% (378/378), done.
	Checking connectivity... done.
	felipe@cloud:~$ cd Node-Whiteboard/
	felipe@cloud:~/Node-Whiteboard$ npm install -d
	npm info it worked if it ends with ok
	npm info using npm@5.3.0
	npm info using node@v8.3.0
	npm info lifecycle heisenbug-whiteboard@1.0.0~preinstall: heisenbug-whiteboard@1.0.0
	npm http fetch GET 200 https://registry.npmjs.org/nko 576ms
	http fetch GET 200 https://registry.npmjs.org/nko/-/nko-0.1.1.tgz 403mslocks/st
	npm info lifecycle nko@0.1.1~preinstall: nko@0.1.1
	npm info linkStuff nko@0.1.1
	npm info lifecycle nko@0.1.1~install: nko@0.1.1
	npm info lifecycle nko@0.1.1~postinstall: nko@0.1.1
	npm info linkStuff heisenbug-whiteboard@1.0.0
	npm info lifecycle heisenbug-whiteboard@1.0.0~install: heisenbug-whiteboard@1.0.0
	npm info lifecycle heisenbug-whiteboard@1.0.0~postinstall: heisenbug-whiteboard@1.0.0
	npm info lifecycle heisenbug-whiteboard@1.0.0~prepublish: heisenbug-whiteboard@1.0.0
	npm info lifecycle heisenbug-whiteboard@1.0.0~prepare: heisenbug-whiteboard@1.0.0
	npm info lifecycle undefined~preshrinkwrap: undefined
	npm info lifecycle undefined~shrinkwrap: undefined
	npm notice created a lockfile as package-lock.json. You should commit this file.
	npm info lifecycle undefined~postshrinkwrap: undefined
	npm WARN heisenbug-whiteboard@1.0.0 No license field.

	added 1 package in 1.846s
	npm info ok
	felipe@cloud:~/Node-Whiteboard$ node server.js
	events.js:182
		  throw er; // Unhandled 'error' event
		  ^

	Error: listen EADDRINUSE :::8080
		at Object._errnoException (util.js:1022:11)
		at _exceptionWithHostPort (util.js:1045:20)
		at Server.setupListenHandle [as _listen2] (net.js:1330:14)
		at listenInCluster (net.js:1378:12)
		at Server.listen (net.js:1478:7)
		at Object.<anonymous> (/home/felipe/Node-Whiteboard/server.js:283:5)
		at Module._compile (module.js:573:30)
		at Object.Module._extensions..js (module.js:584:10)
		at Module.load (module.js:507:32)
		at tryModuleLoad (module.js:470:12)

**Comment by tdryer** [comment]
Sorry, this code has been unmaintained for six years. It probably doesn't work anymore.
